version: "3.8"

x-common-variables: &common-variables
  PUID: 1000
  PGID: 973
  TZ: Etc/UTC

services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    environment:
      <<: *common-variables
      GF_SERVER_ROOT_URL: http://grafana.thecowsaysmoo.net/
      GF_INSTALL_PLUGINS: grafana-clock-panel
    user: '0'
    networks:
      - grafana
      - backend
    ports:
      - 4000:3000
    volumes:
      - /opt/docker/grafana/data:/var/lib/grafana
      - /opt/docker/grafana/config:/etc/grafana
    restart: unless-stopped
    depends_on:
      - cadvisor

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    networks: 
      - grafana
      - backend
    ports:
      - 8085:8080
    volumes:
      - /:/rootfs
      - /var/run:/var/run
      - /sys:/sys
      - /var/lib/docker:/var/lib/docker
      - /dev/disk:/dev/disk
    privileged: true
    devices:
      - /dev/kmsg

networks:
  grafana:
    name: grafana
  backend:
    name: backend
    external: true
