version: '3.9'

x-common-variables: &common-variables
  PUID: 1000
  PGID: 1000
  TZ: Etc/UTC

services:
  cgit:
    image: clearlinux/cgit:latest
    networks:
      - infra-services
    ports:
      - 9100:80
    volumes:
      - C:\Users\yohnt\github:/var/www/cgit
    restart: unless-stopped

  it-tools:
    image: corentinth/it-tools:latest
    networks:
      - infra-services
    ports:
      - 8180:80
    restart: unless-stopped

  uptime-kuma:
    image: louislam/uptime-kuma:1
    networks:
      - infra-services
      - backend
    ports:
      - 3001:3001
    volumes:
      - uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  dockwatch_config:
  uptime-kuma:

networks:
  infra-services:
    name: infra-services
  backend:
    name: backend
    external: true
