version: '3.9'

services:
  it-tools:
    image: corentinth/it-tools:latest
    networks:
      - infra-services
    ports:
      - 8180:80
    restart: unless-stopped

  uptime-kuma:
    image: louislam/uptime-kuma:1
    networks:
      - infra-services
      - backend
    ports:
      - 3001:3001
    volumes:
      - uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  uptime-kuma:

networks:
  infra-services:
    name: infra-services
  backend:
    name: backend
    external: true
