version: '3.9'

services:
  it-tools:
    image: corentinth/it-tools:latest
    networks:
      - infra-services
    ports:
      - 8180:80
    restart: unless-stopped

  uptime-kuma:
    image: louislam/uptime-kuma:1
    networks:
      - infra-services
      - backend
    ports:
      - 3001:3001
    volumes:
      - /opt/docker/uptime-kuma/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    networks:
      - infra-services
      - backend
    ports:
      - 3000:3000
    volumes:
      - /opt/docker/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    networks:
      - infra-services
      - backend
    ports:
      - 9090:9090
    volumes:
      - /opt/docker/prometheus:/etc/prometheus
    restart: unless-stopped

networks:
  infra-services:
    name: infra-services
  backend:
    name: backend
    external: true
