version: '3.9'

x-common-variables: &common-variables
  PUID: 1000
  PGID: 1000
  TZ: Etc/UTC

services:
  pihole:
    image: pihole/pihole:latest
    environment:
      <<: *common-variables
      WEBPASSWORD: ${PIHOLE_PASSWORD}
      MOZILLA_CANARY: true
    networks:
      - infra-services
    ports:
      - 192.168.1.151:53:53/tcp
      - 192.168.1.151:53:53/udp
      - 192.168.1.151:67:67/udp
      - 8600:80
    volumes:
      - pihole_config:/etc/pihole
      - pihole_dnsmasq:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    networks:
      infra-services
      backend
    volumes:
      - gitlab_runner_conf:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes: 
  pihole_config:
  pihole_dnsmasq:
  gitlab_runner_conf:

networks:
  infra-services:
    name: infra-services
  backend:
    name: backend
