version: '3.9'

x-common-variables: &common-variables
  PUID: 1000
  PGID: 1000
  TZ: Etc/UTC

services:
  cgit:
    image: clearlinux/cgit:latest
    networks:
      - infra-services
    ports:
      - 9100:80
    volumes:
      - C:\Users\yohnt\github:/var/www/cgit
    restart: unless-stopped

networks:
  infra-services:
    name: infra-services
