version: "3.8"

x-common-variables: &common-variables
  PUID: 1000
  PGID: 1000
  TZ: Etc/UTC
  TP_THEME: overseerr

services:
  radarr:
    image: linuxserver/radarr:latest
    networks:
      - media-management
      - backend
    environment:
      <<: *common-variables
      UMASK_SET: 022
      DOCKER_MODS: ghcr.io/gilbn/theme.park:radarr
    volumes:
      - D:\Docker\radarr\movies:/movies
      - D:\sabnzbd\download\complete:/downloads
      - D:\Docker\radarr\config:/config
    ports:
      - 7878:7878/tcp
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:develop
    networks:
      - media-management
      - backend
    environment:
      <<: *common-variables
      DOCKER_MODS: ghcr.io/gilbn/theme.park:sonarr
    volumes:
      - D:\Docker\sonarr\config:/config
      - D:\Docker\sonarr\tv:/tv
      - D:\Docker\sonarr\anime:/anime
      - D:\sabnzbd\download\complete:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    networks:
      - media-management
      - backend
    environment:
      <<: *common-variables
      DOCKER_MODS: ghcr.io/gilbn/theme.park:prowlarr
    ports:
      - 9696:9696
    volumes:
      - D:\Docker\prowlarr\config:/config
    restart: unless-stopped

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    user: 1000:1000
    networks:
      - media-management
    volumes:
      - D:\Docker\recyclarr\config:/config
    environment: *common-variables
    restart: unless-stopped

  whisparr:
    image: cr.hotio.dev/hotio/whisparr
    networks:
      - media-management
      - backend
    ports:
      - 6969:6969
    environment:
      <<: *common-variables
      UMASK: 002
      TP_HOTIO: true
    volumes:
      - D:\Docker\whisparr\config:/config
      - D:\Docker\whisparr\data:/data
      - D:\sabnzbd\download\complete:/downloads
      - D:\Docker\scripts\98-themepark-whisparr:/etc/cont-init.d/98-themepark
    restart: unless-stopped

  overseerr:
    image: sctx/overseerr:latest
    networks:
      - media-management
      - backend
    environment: 
      <<: *common-variables
    volumes:
      - overseerr_config:/app/config
    restart: unless-stopped

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    networks:
      - media-management
      - backend
    ports:
      - 8181:8181
    environment:
      <<: *common-variables
      DOCKER_MODS: ghcr.io/gilbn/theme.park:tautulli
    volumes:
      - tautulli_config:/config
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    networks:
      - media-management
    ports:
      - 6767:6767
    environment:
      <<: *common-variables
    volumes:
      - bazarr_config:/config
      - D:\Docker\sonarr\tv:/tv
      - D:\Docker\sonarr\anime:/anime
      - D:\Docker\radarr\movies:/movies
    restart: unless-stopped

  lazylibrarian:
    image: lscr.io/linuxserver/lazylibrarian:latest
    networks:
      - media-management
      - backend
    ports:
      - 5299:5299
    environment:
      <<: *common-variables
      DOCKER_MODS: linuxserver/calibre-web:calibre|linuxserver/mods:lazylibrarian-ffmpeg
    volumes:
      - lazylibrarian_config:/config
      - D:\sabnzbd\download\complete:/downloads
      - D:\Docker\lazylibrarian\books:/books
    restart: unless-stopped

volumes:
  tautulli_config:
  overseerr_config:
  bazarr_config:
  lazy_librarian:

networks:
  media-management:
    name: media-management
  backend:
    name: backend
    external: true
