version: "3.8"

x-common-variables: &common-variables
  PUID: 1000
  PGID: 1000
  TZ: Etc/UTC
  TP_THEME: overseerr

services:
  radarr:
    image: linuxserver/radarr:latest
    networks:
      - media-management
      - backend
    environment:
      <<: *common-variables
      UMASK_SET: 022
      DOCKER_MODS: ghcr.io/gilbn/theme.park:radarr
    volumes:
      - D:\data:/data
      - D:\Docker\radarr\config:/config
    ports:
      - 7878:7878/tcp
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:develop
    networks:
      - media-management
      - backend
    environment:
      <<: *common-variables
      DOCKER_MODS: ghcr.io/gilbn/theme.park:sonarr
    volumes:
      - D:\Docker\sonarr\config:/config
      - D:\data:/data
    ports:
      - 8989:8989
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    networks:
      - media-management
      - backend
    environment:
      <<: *common-variables
      DOCKER_MODS: ghcr.io/gilbn/theme.park:prowlarr
    ports:
      - 9696:9696
    volumes:
      - D:\Docker\prowlarr\config:/config
    restart: unless-stopped

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    user: 1000:1000
    networks:
      - media-management
    volumes:
      - D:\Docker\recyclarr\config:/config
    environment: *common-variables
    restart: unless-stopped

  whisparr:
    image: cr.hotio.dev/hotio/whisparr
    networks:
      - media-management
      - backend
    ports:
      - 6969:6969
    environment:
      <<: *common-variables
      UMASK: 002
      TP_HOTIO: true
    volumes:
      - D:\Docker\whisparr\config:/config
      - D:\data:/data
      - D:\Docker\scripts\98-themepark-whisparr:/etc/cont-init.d/98-themepark
    restart: unless-stopped

  overseerr:
    image: sctx/overseerr:latest
    networks:
      - media-management
      - backend
    environment: 
      <<: *common-variables
    volumes:
      - overseerr_config:/app/config
    restart: unless-stopped

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    networks:
      - media-management
      - backend
    ports:
      - 8181:8181
    environment:
      <<: *common-variables
      DOCKER_MODS: ghcr.io/gilbn/theme.park:tautulli
    volumes:
      - tautulli_config:/config
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    networks:
      - media-management
    ports:
      - 6767:6767
    environment:
      <<: *common-variables
    volumes:
      - bazarr_config:/config
      - D:\data\media:/media
    restart: unless-stopped

  lazylibrarian:
    image: lscr.io/linuxserver/lazylibrarian:latest
    networks:
      - media-management
      - backend
    ports:
      - 5299:5299
    environment:
      <<: *common-variables
      DOCKER_MODS: linuxserver/calibre-web:calibre|linuxserver/mods:lazylibrarian-ffmpeg
    volumes:
      - lazylibrarian_config:/config
      - D:\data:/data
    restart: unless-stopped

  notifiarr:
    image: golift/notifiarr
    hostname: notifiarr
    networks:
      - media-management
      - backend
    ports:
      - 5454:5454
    environment:
      <<: *common-variables
      DN_API_KEY: ${NOT_APIKEY}
      DN_RADARR_0_NAME: "Radarr"
      DN_RADARR_0_URL: "http://192.168.1.150:7878"
      DN_RADARR_0_API_KEY: ${RAD_APIKEY}
      DN_PROWLARR_0_NAME: "Prowlarr"
      DN_PROWLARR_0_URL: "http://192.168.1.150:9696"
      DN_PROWLARR_0_API_KEY: ${PRO_APIKEY}
      DN_SONARR_0_NAME: "Sonarr"
      DN_SONARR_0_URL: "http://192.168.1.150:8989"
      DN_SONARR_0_API_KEY: ${SON_APIKEY}
      DN_SABNZBD_0_NAME: "SABnzbd"
      DN_SABNZBD_0_URL: "http://192.168.1.150:8080"
      DN_SABNZBD_0_API_KEY: ${SAB_APIKEY}
      DN_PLEX_0_URL: ${PLEX_URL}
      DN_PLEX_TOKEN: ${PLEX_TOK}
      DN_TAUTULLI_NAME: "Tautulli"
      DN_TAUTULLI_URL: "http://192.168.1.150:8181"
      DN_TAUTULLI_API_KEY: ${TAT_APIKEY}
    volumes:
      - notifiarr_config:/config
      - D:\Data:/data
      - /etc/machine-id:/etc/machine-id

volumes:
  tautulli_config:
  overseerr_config:
  bazarr_config:
  lazylibrarian_config:
  notifiarr_config:

networks:
  media-management:
    name: media-management
  backend:
    name: backend
    external: true
