version: '3.9'
services:
  kavita:
    image: kizaing/kavita:latest
    networks:
      - public-services
    volumes:
        - /opt/data:/data
        - /opt/docker/kavita/config:/kavita/config
    restart: unless-stopped

  vault:
    image: vaultwarden/server:latest
    networks:
      - public-services
    environment:
      SIGNUPS_ALLOWED: true
      ADMIN_TOKEN: ${VAULT_TOKEN}
    volumes:
      - /opt/docker/vault/data:/data
    restart: unless-stopped

  pastebin:
    image: wantguns/bin
    networks:
      - public-services
    environment:
      BIN_PORT: 6163
      BIN_CLIENT_DESC: moo
    volumes:
      - /opt/docker/pastebin/data:/upload

networks:
  public-services:
    name: public-services
  backend:
    name: backend
    external: true 
