version: '3.9'
services:
  kavita:
    image: kizaing/kavita:latest
    networks:
      - public-services
    volumes:
        - D:\Docker\kavita\comics:/comics
        - D:\Docker\kavita\organized:/comics-organized
        - D:\Docker\kavita\config:/kavita/config
    restart: unless-stopped

  vault:
    image: vaultwarden/server:latest
    networks:
      - public-services
    environment:
      SIGNUPS_ALLOWED: true
      ADMIN_TOKEN: ${VAULT_TOKEN}
    volumes:
      - vault_data:/data
    restart: unless-stopped

  caddy:
    image: caddy:2.7
    networks:
      - public-services
      - backend
    cap_add:
      - NET_ADMIN
    ports:
      - 80:80
      - 443:443
      - "443:443/udp"
    volumes:
      - D:\Docker\caddy\caddy:/usr/bin/caddy
      - D:\Docker\caddy\Caddyfile:/etc/caddy/Caddyfile
      - D:\Docker\caddy\data:/data
      - caddy_config:/config

  pastebin:
    image: wantguns/bin
    networks:
      - public-services
    environment:
      BIN_PORT: 6163
      BIN_CLIENT_DESC: moo
    volumes:
      - pastebin_data:/upload

  foundry:
    image: felddy/foundryvtt:release
    networks:
      - public-services
    environment:
      FOUNDRY_PASSWORD: ${F_PWD}
      FOUNDRY_USERNAME: ${F_USER}
      FOUNDRY_ADMIN_KEY: ${F_ADMIN_KEY}
      FOUNDRY_RELEASE_URL: ${F_URL}
    volumes:
      - D:\Docker\foundryvtt\data:/data

volumes:
  vault_data:
  caddy_data:
  caddy_config:
  pastebin_data:

networks:
  public-services:
    name: public-services
  backend:
    name: backend
