version: '3.9'
services:
  kavita:
    image: kizaing/kavita:latest
    networks:
      - public-services
    volumes:
        - D:\Docker\kavita\comics:/comics
        - D:\Docker\kavita\organized:/comics-organized
        - D:\Docker\kavita\config:/kavita/config
    restart: unless-stopped

  vault:
    image: vaultwarden/server:latest
    networks:
      - public-services
    environment:
      SIGNUPS_ALLOWED: true
      ADMIN_TOKEN: ${VAULT_TOKEN}
    volumes:
      - vault_data:/data
    restart: unless-stopped

  caddy:
    image: caddy:2.7
    networks:
      - public-services
      - backend
    cap_add:
      - NET_ADMIN
    ports:
      - 80:80
      - 443:443
      - "443:443/udp"
    volumes:
      - D:\Docker\caddy\caddy:/usr/bin/caddy
      - D:\Docker\caddy\Caddyfile:/etc/caddy/Caddyfile
      - D:\Docker\caddy\data:/data
      - caddy_config:/config

  pastefy-db:
    image: mariadb:10.11
    volumes:
      - pastefy_dbvol:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: ${PASTEFY_DB_ROOT_PWD}
      MYSQL_DATABASE: ${PASTEFY_DB}
      MYSQL_USER: ${PASTEFY_DB_USER}
      MYSQL_PASSWORD: ${PASTEFY_DB_PWD}

  pastefy:
    depends_on:
      - pastefy-db
    image: interaapps/pastefy:latest
    environment:
      HTTP_SERVER_PORT: 80
      HTTP_SERVER_CORS: "*"
      DATABASE_DRIVER: mysql
      DATABASE_NAME: ${PASTEFY_DB}
      DATABASE_USER: ${PASTEFY_DB_USER}
      DATABASE_PASSWORD: ${PASTEFY_DB_PWD}
      DATABASE_HOST: public-services-pastefy-db-1 
      DATABASE_PORT: 3306
      SERVER_NAME: "https://pastefy.thecowsaysmoo.net"

volumes:
  vault_data:
  caddy_data:
  caddy_config:
  pastefy_dbvol:

networks:
  public-services:
    name: public-services
  backend:
    name: backend
