version: '3.9'
services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    networks:
      - public-services
    ports:
      - 80:80 
      - 443:443
      - 81:81 
    volumes:
      - D:\Docker\npm\data:/data
      - D:\Docker\npm\letsencrypt:/etc/letsencrypt
        
  kavita:
    image: kizaing/kavita:latest
    networks:
      - public-services
    volumes:
        - D:\Docker\kavita\comics:/comics
        - D:\Docker\kavita\organized:/comics-organized
        - D:\Docker\kavita\config:/kavita/config
    restart: unless-stopped

networks:
  public-services:
    name: public-services
