version: '3.9'
services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    networks:
      - public-services
    ports:
      - 192.168.1.150:800:80 
      - 192.168.1.150:4433:443
      - 192.168.1.150:81:81 
    volumes:
      - D:\Docker\npm\data:/data
      - D:\Docker\npm\letsencrypt:/etc/letsencrypt
    restart: unless-stopped
        
  kavita:
    image: kizaing/kavita:latest
    networks:
      - public-services
    volumes:
        - D:\Docker\kavita\comics:/comics
        - D:\Docker\kavita\organized:/comics-organized
        - D:\Docker\kavita\config:/kavita/config
    restart: unless-stopped

  vault:
    image: vaultwarden/server:latest
    networks:
      - public-services
    environment:
      SIGNUPS_ALLOWED: true
      ADMIN_TOKEN: ${VAULT_TOKEN}
    volumes:
      - vault_data:/data
    restart: unless-stopped

  actual:
    image: actualbudget/actual-server:latest
    networks:
      - public-services
    volumes:
      - actual_data:/data
    restart: unless-stopped

  thelounge:
    image: ghcr.io/thelounge/thelounge:latest
    networks:
      - public-services
    volumes:
      - thelounge_config:/var/opt/thelounge
    restart: unless-stopped

  bookstack:
    image: lscr.io/linuxserver/bookstack
    networks:
      - public-services
      - backend
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=https://stack.thecowsaysmoo.net
      - DB_HOST=public-services-bookstack_db-1
      - DB_PORT=3306
      - DB_USER=${DBUSER}
      - DB_PASS=${DBPASS}
      - DB_DATABASE=${DBDATABASE}
    volumes:
      - bookstack_app_data:/config
    restart: unless-stopped
    depends_on:
      - bookstack_db

  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    networks:
      - backend
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${DBROOTPASS}
      - TZ=Etc/UTC
      - MYSQL_DATABASE=${DBDATABASE}
      - MYSQL_USER=${DBUSER}
      - MYSQL_PASSWORD=${DBPASS}
    volumes:
      - bookstack_db_data:/config
    restart: unless-stopped

  gogs:
    image: gogs/gogs
    networks:
      - public-services
    ports:
      - 22:22
    volumes:
      gogs_data:/data
    restart: unless-stopped

volumes:
  vault_data:
  actual_data:
  thelounge_config:
  bookstack_app_data:
  bookstack_db_data:
  gogs_data:

networks:
  public-services:
    name: public-services
  backend:
    name: backend
