version: '3.9'
services:
  kavita:
    image: kizaing/kavita:latest
    networks:
      - public-services
    volumes:
        - D:\Docker\kavita\comics:/comics
        - D:\Docker\kavita\organized:/comics-organized
        - D:\Docker\kavita\config:/kavita/config
    restart: unless-stopped

  vault:
    image: vaultwarden/server:latest
    networks:
      - public-services
    environment:
      SIGNUPS_ALLOWED: true
      ADMIN_TOKEN: ${VAULT_TOKEN}
    volumes:
      - vault_data:/data
    restart: unless-stopped

  traefix:
    image: traefik:v2.10
    networks:
      - public-services
      - backend
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - D:\Docker\traefik\traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro

  whoami:
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host('whoami.thecowsaysmoo.net')"
      - "traefik.http.routers.whoami.entrypoints=web"

volumes:
  vault_data:

networks:
  public-services:
    name: public-services
  backend:
    name: backend
