version: '3.9'
services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    networks:
      - public-services
    ports:
      - 80:80 
      - 443:443
      - 81:81 
    volumes:
      - D:\Docker\npm\data:/data
      - D:\Docker\npm\letsencrypt:/etc/letsencrypt
    restart: unless-stopped
        
  kavita:
    image: kizaing/kavita:latest
    networks:
      - public-services
    volumes:
        - D:\Docker\kavita\comics:/comics
        - D:\Docker\kavita\organized:/comics-organized
        - D:\Docker\kavita\config:/kavita/config
    restart: unless-stopped

  vault:
    image: vaultwarden/server:latest
    networks:
      - public-services
    environment:
      SIGNUPS_ALLOWED: true
      ADMIN_TOKEN: ${VAULT_TOKEN}
    volumes:
      - vault_data:/data
    restart: unless-stopped

  actual:
    image: actualbudget/actual-server:latest
    networks:
      - public-services
    volumes:
      - actual_data:/data
    restart: unless-stopped

  gitlab:
    image: gitlab/gitlab-ee:latest
    networks:
      - public-services
      - backend
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.thecowsaysmoo.net'
    ports:
      - 22:22
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    shm_size: 256m
    restart: unless-stopped

  selfoss:
    image: rsprta/selfoss
    networks:
      - public-services
    ports:
      - 8888:8888
    volumes:
      - selfoss_data:/selfoss/data
    restart: unless-stopped

volumes:
  vault_data:
  actual_data:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
  selfoss_data:

networks:
  public-services:
    name: public-services
  backend:
    name: backend
    external: true
