version: '3.9'
services:
  kavita:
    image: kizaing/kavita:latest
    networks:
      - public-services
    volumes:
        - /opt/data/comics/incoming:/comics
        - /opt/data/comics/organized:/comics-organized
        - kavita_config:/kavita/config
    restart: unless-stopped

  vault:
    image: vaultwarden/server:latest
    networks:
      - public-services
    environment:
      SIGNUPS_ALLOWED: true
      ADMIN_TOKEN: ${VAULT_TOKEN}
    volumes:
      - vault_data:/data
    restart: unless-stopped

  pastebin:
    image: wantguns/bin
    networks:
      - public-services
    environment:
      BIN_PORT: 6163
      BIN_CLIENT_DESC: moo
    volumes:
      - pastebin_data:/upload

volumes:
  vault_data:
  caddy_config:
  kavita_config:
  pastebin_data:

networks:
  public-services:
    name: public-services
  backend:
    name: backend
    externa: true 
