version: '3.9'
services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    networks:
      - public-services
      - backend
    ports:
      - 80:80 
      - 443:443
      - 81:81 
    volumes:
      - D:\Docker\npm\data:/data
      - D:\Docker\npm\letsencrypt:/etc/letsencrypt
    restart: unless-stopped
        
  kavita:
    image: kizaing/kavita:latest
    networks:
      - public-services
    volumes:
        - D:\Docker\kavita\comics:/comics
        - D:\Docker\kavita\organized:/comics-organized
        - D:\Docker\kavita\config:/kavita/config
    restart: unless-stopped

  vault:
    image: vaultwarden/server:latest
    networks:
      - public-services
    environment:
      SIGNUPS_ALLOWED: true
      ADMIN_TOKEN: ${VAULT_TOKEN}
    volumes:
      - vault_data:/data
    restart: unless-stopped

  actual:
    image: actualbudget/actual-server:latest
    networks:
      - public-services
    volumes:
      - actual_data:/data
    restart: unless-stopped

  thelounge:
    image: ghcr.io/thelounge/thelounge:latest
    networks:
      - public-services
    volumes:
      - thelounge_config:/var/opt/thelounge
    restart: unless-stopped

  gogs:
    image: gogs/gogs
    networks:
      - public-services
    ports:
      - 22:22
    volumes:
      - gogs_data:/data
    restart: unless-stopped

  foundry:
    image: felddy/foundryvtt:release
    hostname: foundry.thecowsaysmoo.net
    networks:
      - public-services
    volumes:
      - D:\Docker\foundryvtt\data:/data
    environment:
      - FOUNDRY_PASSWORD="${F_PASS}"
      - FOUNDRY_USERNAME="${F_USER}"
      - FOUNDRY_ADMIN_KEY="${F_ADMIN}"

volumes:
  vault_data:
  actual_data:
  thelounge_config:
  gogs_data:

networks:
  public-services:
    name: public-services
  backend:
    name: backend
